use_frameworks!
project 'JSwiftON.xcodeproject'

target 'JSwiftON_Example' do
  pod 'JSwiftON', :path => '../'

  target 'JSwiftON_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
